### ISSUE TITLE
Upload with method PUT not send parameters

### ISSUE THREAD

**Issue by darlaneduardo** [apache/cordova-plugin-file-transfer#204]
I have a problem with sending image using method put. The parameters not sending. 

var options = {
      fileKey: "foto",
      fileName: 'foto.jpg',
      chunkedMode: false,
      params: {'ok': 'teste'},
      httpMethod: 'PUT'
};

**Comment by abutizi** [comment]
I have same issue :(

**Comment by Freakazo** [comment]
Same issue here: Andriod Q Pixel 2 in emulator.

**Comment by timbru31** [comment]
I'm closing the issue due to staleness and missing required information from the template.
If the issue persists, please open a new one, follow the template and include a minimum reproducible example. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
