### ISSUE TITLE
Uncaught ReferenceError: loadingStatus is not defined 

### ISSUE THREAD

**Issue by FreddyCrugger** [apache/cordova-plugin-file-transfer#206]
Hello,

Phonegap 8.0.0
Android 7.0.0

On this line:
loadingStatus.setPercentage(progressEvent.loaded / progressEvent.total);

I keep seeing in the console "Uncaught ReferenceError: loadingStatus is not defined"

**Comment by janpio** [comment]
Hm, this might very well be a bug in the documentation. `loadingStatus` only appeary in the README and the tests, same for `.setPercentage(...)`. 

So that code probably doesn't work as it should but is some UI artifact that ~~maybe was supported before or is just a bad copy/paste from somewhere.~~ was there from the start when the documentation was created: https://github.com/apache/cordova-plugin-file-transfer/commit/102e7afc9399fc7cb2c15e7c6bfd319c9dab3aac#diff-5db2c860d4e7e5ef74eb7cfc33d99f8eR137

**Comment by FreddyCrugger** [comment]
Thanks for the reply. I understand now :-)

**Comment by janpio** [comment]
Let's leave this issue open as it is a honest bug in the README that should be fixed.
