### ISSUE TITLE
File transfer coudnt trigger URL 

### ISSUE THREAD

**Issue by madhuranga-smarttimes** [apache/cordova-plugin-file-transfer#276]
Filetransfer show error code 3 when call download function with http_status:401

Version : "cordova-plugin-file-transfer": "^1.7.1",
ionic 5 with capacitor

**Comment by breautek** [comment]
Status code 401 means "Unauthorized". The server has acknowledged your request and decided that you're for some reason unauthorized.

From the information you've provided, nothing indicates a problem with this plugin. You should look at the API documentation of the server you're hitting to determine what is missing or when the server returns `401` status code.

If you feel like this is a bug with this plugin, I'll ask you to recreate this issue with the issue form filled out rather than deleting the form provided.

**Comment by madhuranga-smarttimes** [comment]
The thing is it worked perfectly with the ionic 3 version and recently we revamp with ionic 5. After we get this error. Mostly I guess some of the permission issues from client-side.

**Comment by conquor** [comment]
same error to me

**Comment by ArturV93** [comment]
Same issue tried several services to download file from
