### ISSUE TITLE
Run into errors when building in cordova-ios 6.1.1

### ISSUE THREAD

**Issue by shanlin2dltk** [apache/cordova-plugin-file-transfer#279]
# Bug Report
Build works fine for cordova-ios 5.1.1 version.  After upgrading to cordova-ios 6.1.1 version, the build fails.  The issues can be replicated in a simple Helloworld app, with the following error messages:
`xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/shanlin/build/extjs_cp_time/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
`
cordova client 9.0.0 is used.

**Comment by breautek** [comment]
This plugin was recently became undeprecated and there are known issues with this plugin for `cordova-ios@6.x`.

Can you test this against the development version of this plugin to see if the error goes away on our `master` branch?

```
cordova plugin remove cordova-plugin-file-transfer
cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git#master
```

**Comment by shanlin2dltk** [comment]
> This plugin was recently became undeprecated and there are known issues with this plugin for `cordova-ios@6.x`.
> 
> Can you test this against the development version of this plugin to see if the error goes away on our `master` branch?
> 
> ```
> cordova plugin remove cordova-plugin-file-transfer
> cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git#master
> ```

The build works when using this dev version in master branch.

**Comment by breautek** [comment]
Thank you for letting us know. This means that issue was already resolved and the fix should be available in our next release (no current ETA).

It's important to note that the development versions aren't suitable for production code. But if this issue is a huge blocker for you, then you should fork the repo, or at least pin to a specific commit so your dependency doesn't unexpectedly change (perhaps in a breaking way) in your project.

ie: `cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git#4a1e766fb7535637acdda00dd6700f42379daca3`

Where `4a1e766fb7535637acdda00dd6700f42379daca3` is the current commit hash of master at this time of writing.
