### ISSUE TITLE
When will master be released?

### ISSUE THREAD

**Issue by dtarnawsky** [apache/cordova-plugin-file-transfer#312]
# Bug Report

## Problem
You've fixed a lot of great stuff but have never released it.

### What is expected to happen?
npm should have the latest code from master.

### What does actually happen?
You get stuff from 3 years ago :(

## Information

The current version of the plugin on npm has compilation issues. Fixes have been done in master for this, android 10 support etc but no release has been done to allow people to install from npm (and use thing like npm proxies etc).

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
cordova-plugin-file, a dependency of this plugin is kind of been a blocker for properly supporting API 30.

> You get stuff from 3 years ago

Part of this is because this plugin was deprecated, but the community has decided a few months ago to revive it, namely because relying on pure JS implementations doesn't work well when it comes to handling large files due to the lack of streaming support.

Due to the volunteer nature of Apache projects, we cannot really give any timelines on when packages will be released.
