### ISSUE TITLE
This plugin seems to be no longer supported

### ISSUE THREAD

**Issue by massimilianocom** [apache/cordova-plugin-file-transfer#342]
On cordova 11 when I start the android emulator it gives me this error:

```
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
45 actionable tasks: 8 executed, 37 up-to-date
```

and stop not building me.

If I uninstall the plugin everything works perfectly

**Comment by breautek** [comment]
Current release is old, out-dated and isn't compatible with modern tooling. The reason for this is because the plugin was deprecated, in favour of standard browser XHR features.

Since then, we have "un-deprecated" due to issues with dealing large files when using standard browser XHR features, but a release hasn't been made as development and updates are still ongoing. Please test with master dev version of this plugin to see if it solves your issue.

If it does not, then please create a new issue with the issue template filled out.

Kind regards,
