### ISSUE TITLE
how do i install 2.0.0-dev?

### ISSUE THREAD

**Issue by thomstark** [apache/cordova-plugin-file-transfer#349]
I cannot find how to install v2.0.0-dev into my project. I have that version installed in another project but cannot remember the steps necessary to get it installed in my current project. 

When I run cordova plugin add cordova-plugin-file-transfer it installs 1.7.1. If I specify @latest or @2.0.0-dev it gives me errors. 

I tried adding `"@nutshellapps/cordova-plugin-file-transfer": "^2.0.0-dev"` to my dependencies in package.json but i'm not sure where to go from there.

**Comment by breautek** [comment]
Apache does not release dev versions to NPM. `@nutshellapps/cordova-plugin-file-transfer` is not a package that Apache manages. It could have been published with or without modifications or at any stage of `2.0.0` development, which is still not complete.

Apache does not advise using development versions of Apache software as they have not be voted on for release. But you can install development versions for testing/development purposes via git (Git client required).

Example:
```
cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git#master
```

If you already have the plugin installed, you'll have to `cordova plugin remove` it first before trying to add a new version.

The current NPM release is a formally deprecated version of the file transfer which doesn't work with current platform releases and is why it's severely out-dated. Since then it has been voted on to revive the project due to issues with handling large files, but the revival is still a work in progress.

Last time I tested the master development branch, it is **mostly** working, but there are tests that is failing in the CI and currently that is the main blocker for an actual 2.x release. Therefore you're mileage may vary. We'd be happy to see volunteers help resolve the failing tests.

If interested in volunteering, reach out to our [Slack Community](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) or our [Dev Mailing List](https://cordova.apache.org/contact/).
